import { Event, createDefaultFloorPlans, createDefaultTablescapes } from "./types";

export function getSeedData(): Event[] {
  return [
    {
      id: "evt-1",
      name: "Johnson Wedding",
      date: "2026-06-15",
      venue: "The Grand Ballroom",
      clientName: "Sarah & James Johnson",
      clientEmail: "sarah@example.com",
      status: "confirmed",
      floorPlanJSON: null,
      floorPlans: [
        ...createDefaultFloorPlans(),
      ],
      tablescapes: createDefaultTablescapes(),
      files: [
        {
          id: "f1",
          name: "Wedding Contract.pdf",
          type: "contract",
          url: "#",
          storagePath: null,
          uploadedAt: "2026-01-10T00:00:00Z",
        },
        {
          id: "f2",
          name: "Mood Board - Rustic Elegance.jpg",
          type: "moodboard",
          url: "#",
          storagePath: null,
          uploadedAt: "2026-01-15T00:00:00Z",
        },
      ],
      timeline: [
        { id: "t1", title: "Finalize guest list", dueDate: "2026-03-01", completed: true, order: 1 },
        { id: "t2", title: "Confirm catering menu", dueDate: "2026-04-01", completed: false, order: 2 },
        { id: "t3", title: "Final floor plan approval", dueDate: "2026-05-01", completed: false, order: 3 },
        { id: "t4", title: "Rehearsal dinner", dueDate: "2026-06-14", completed: false, order: 4 },
      ],
      vendors: [
        { id: "v1", name: "Petal & Bloom", category: "flowers", contact: "Maria Chen", phone: "555-0101", email: "maria@petalbloom.com", notes: "White garden roses, greenery arches", mealChoice: "", contractTotal: 0, payments: [] },
        { id: "v2", name: "Golden Hour Photography", category: "photography", contact: "James Kirk", phone: "555-0102", email: "james@goldenhour.com", notes: "8hr package, second shooter included", mealChoice: "Chicken", contractTotal: 0, payments: [] },
        { id: "v3", name: "La Belle Cuisine", category: "catering", contact: "Chef Antoine", phone: "555-0103", email: "catering@labelle.com", notes: "3-course plated dinner, 150 guests", mealChoice: "", contractTotal: 0, payments: [] },
      ],
      questionnaires: [],
      invoices: [],
      expenses: [],
      guests: [],
      colorPalette: [],
      moodBoard: [],
      discoveredVendors: [],
      contracts: [],
      budget: [],
      messages: [],
      archivedAt: null,
      shareToken: '',
      weddingPageEnabled: false,
      weddingSlug: null,
      weddingHeadline: '',
      weddingStory: '',
      weddingHeroStoragePath: '',
      weddingVenueDetails: {},
      weddingTravelInfo: [],
      weddingFaq: [],
      weddingRegistryLinks: [],
      weddingSectionsOrder: ['hero','story','schedule','venue','rsvp','faq','travel','registry'],
      schedule: [
        { id: "s1", time: "10:00", title: "Bridal party prep begins", notes: "Hair & makeup at venue suite", showOnWeddingPage: true },
        { id: "s2", time: "12:00", title: "Groom & groomsmen arrive", notes: "", showOnWeddingPage: true },
        { id: "s3", time: "14:00", title: "Ceremony begins", notes: "Guests seated 30 min prior", showOnWeddingPage: true },
        { id: "s4", time: "14:45", title: "Cocktail hour", notes: "Garden terrace — lawn games, canapés", showOnWeddingPage: true },
        { id: "s5", time: "17:00", title: "Reception doors open", notes: "", showOnWeddingPage: true },
        { id: "s6", time: "18:00", title: "First dance & introductions", notes: "", showOnWeddingPage: true },
        { id: "s7", time: "18:30", title: "Dinner service", notes: "3-course plated", showOnWeddingPage: true },
        { id: "s8", time: "20:30", title: "Cake cutting", notes: "", showOnWeddingPage: true },
        { id: "s9", time: "21:00", title: "Dancing & open bar", notes: "", showOnWeddingPage: true },
        { id: "s10", time: "23:00", title: "Last dance & send-off", notes: "Sparkler exit", showOnWeddingPage: true },
      ],
      createdAt: "2026-01-05T00:00:00Z",
      updatedAt: "2026-01-15T00:00:00Z",
    },
    {
      id: "evt-2",
      name: "Martinez Corporate Gala",
      date: "2026-09-20",
      venue: "Skyline Rooftop Venue",
      clientName: "Elena Martinez",
      clientEmail: "elena@corpevents.com",
      status: "planning",
      floorPlanJSON: null,
      floorPlans: [
        ...createDefaultFloorPlans(),
      ],
      tablescapes: createDefaultTablescapes(),
      files: [],
      timeline: [
        { id: "t5", title: "Venue walkthrough", dueDate: "2026-05-15", completed: false, order: 1 },
        { id: "t6", title: "AV requirements", dueDate: "2026-06-01", completed: false, order: 2 },
        { id: "t7", title: "Send invitations", dueDate: "2026-07-01", completed: false, order: 3 },
      ],
      vendors: [],
      questionnaires: [],
      invoices: [],
      expenses: [],
      guests: [],
      colorPalette: [],
      moodBoard: [],
      discoveredVendors: [],
      contracts: [],
      budget: [],
      messages: [],
      archivedAt: null,
      shareToken: '',
      weddingPageEnabled: false,
      weddingSlug: null,
      weddingHeadline: '',
      weddingStory: '',
      weddingHeroStoragePath: '',
      weddingVenueDetails: {},
      weddingTravelInfo: [],
      weddingFaq: [],
      weddingRegistryLinks: [],
      weddingSectionsOrder: ['hero','story','schedule','venue','rsvp','faq','travel','registry'],
      schedule: [
        { id: "s11", time: "17:00", title: "Doors open — cocktail reception", notes: "", showOnWeddingPage: true },
        { id: "s12", time: "18:00", title: "Welcome remarks", notes: "CEO address, 10 min", showOnWeddingPage: true },
        { id: "s13", time: "18:15", title: "Dinner service", notes: "", showOnWeddingPage: true },
        { id: "s14", time: "19:30", title: "Awards & recognition", notes: "", showOnWeddingPage: true },
        { id: "s15", time: "21:00", title: "Entertainment & dancing", notes: "", showOnWeddingPage: true },
        { id: "s16", time: "23:00", title: "Event closes", notes: "", showOnWeddingPage: true },
      ],
      createdAt: "2026-02-20T00:00:00Z",
      updatedAt: "2026-02-20T00:00:00Z",
    },
    {
      id: "evt-3",
      name: "Patel Anniversary Party",
      date: "2026-04-10",
      venue: "Garden Terrace",
      clientName: "Raj & Priya Patel",
      clientEmail: "raj@example.com",
      status: "confirmed",
      floorPlanJSON: null,
      floorPlans: [
        ...createDefaultFloorPlans(),
      ],
      tablescapes: createDefaultTablescapes(),
      files: [
        {
          id: "f3",
          name: "Anniversary Photos.zip",
          type: "photo",
          url: "#",
          storagePath: null,
          uploadedAt: "2026-02-01T00:00:00Z",
        },
      ],
      timeline: [
        { id: "t8", title: "Flower arrangements confirmed", dueDate: "2026-03-15", completed: true, order: 1 },
        { id: "t9", title: "Final headcount", dueDate: "2026-03-25", completed: false, order: 2 },
      ],
      vendors: [],
      questionnaires: [],
      invoices: [],
      expenses: [],
      guests: [],
      colorPalette: [],
      moodBoard: [],
      discoveredVendors: [],
      contracts: [],
      budget: [],
      messages: [],
      archivedAt: null,
      shareToken: '',
      weddingPageEnabled: false,
      weddingSlug: null,
      weddingHeadline: '',
      weddingStory: '',
      weddingHeroStoragePath: '',
      weddingVenueDetails: {},
      weddingTravelInfo: [],
      weddingFaq: [],
      weddingRegistryLinks: [],
      weddingSectionsOrder: ['hero','story','schedule','venue','rsvp','faq','travel','registry'],
      schedule: [
        { id: "s17", time: "15:00", title: "Guests arrive", notes: "Champagne welcome", showOnWeddingPage: true },
        { id: "s18", time: "15:30", title: "Garden ceremony", notes: "Vow renewal, 20 min", showOnWeddingPage: true },
        { id: "s19", time: "16:00", title: "Reception & dinner", notes: "", showOnWeddingPage: true },
        { id: "s20", time: "18:00", title: "Speeches & toasts", notes: "", showOnWeddingPage: true },
        { id: "s21", time: "19:00", title: "Dancing", notes: "", showOnWeddingPage: true },
        { id: "s22", time: "21:00", title: "Evening ends", notes: "", showOnWeddingPage: true },
      ],
      createdAt: "2026-01-20T00:00:00Z",
      updatedAt: "2026-02-01T00:00:00Z",
    },
  ];
}
